name: Lint & Build

on:
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: read
  checks: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://dev-preview.sssupport.shop
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Retrive caches
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Enable corepack
        run: corepack enable
      - name: Install project
        run: yarn install --immutable
      - name: Check Prettier
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Generate lint failure report
        if: failure()
        run: yarn lint:export
      - name: Annotate Code Linting Results
        if: failure()
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'eslint-report.json'
      - name: Build
        run: yarn build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_REDIRECT_URI: ${{ vars.VITE_REDIRECT_URI }}
          VITE_REST_API_KEY: ${{ secrets.VITE_REST_API_KEY }}
      - name: Create a status check
        uses: actions/github-script@v7
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |
            const sha = process.env.SHA
            const result = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'pending',
              target_url: 'https://dev-preview.sssupport.shop',
              description: '배포 중...',
              context: '미리보기 배포',
            })
      - name: Compress build artifacts
        run: tar -cvf ./dist.tar ./dist
      - name: Upload with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist.tar'
          target: '/home/ubuntu/'
      - name: Extract artifact with SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: ubuntu
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            tar -xvf ./dist.tar ./dist
            sudo rm -rf ${{ vars.DEPLOYMENT_PATH }}
            sudo mv ./dist ${{ vars.DEPLOYMENT_PATH }}
            rm -rf ./dist
            rm -f ./dist.tar
      - name: Make a success status check
        if: success()
        uses: actions/github-script@v7
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |
            const sha = process.env.SHA
            const result = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'success',
              target_url: 'https://dev-preview.sssupport.shop',
              description: '배포 성공 - 좌측 링크를 눌러 접속하세요',
              context: '미리보기 배포',
            })
      - name: Make a failure status check
        if: failure()
        uses: actions/github-script@v7
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          script: |
            const sha = process.env.SHA
            const result = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'failure',
              description: '배포 실패',
              context: '미리보기 배포',
            })
